echo "GIT Clone remote resources to your local"
git clone --progress -v "https://github.com/MechatronicBeing/resources.git"
git clone --progress -v "https://github.com/MechatronicBeing/resources-comics.git"
git clone --progress -v "https://github.com/MechatronicBeing/resources-video-games-music-1.git"
git clone --progress -v "https://github.com/MechatronicBeing/resources-video-games-music-2.git"
